name: "openwrt on host"
rootfs: /var/lib/openwrt/.rootfs
container_name: openwrt-on-podman
service_name: openwrt-on-podman
host_name: "routerpm"
data_path: /var/lib/openwrt
netns: op_on_host
netns_path: /run/netns/op_on_host
cgroup_parent: machine.slice
memory: 512m
# always, unless-stopped, no
restart_policy: always
extra_params:
  - "--replace --read-only"
env: []
mount:
  - "/var/lib/openwrt/config:/etc/config:rw"
sysctl:
  - "net.ipv6.conf.all.forwarding=1"
  - "net.ipv4.ip_forward=1"
  - "net.ipv4.conf.default.rp_filter=2"
  - "net.ipv4.conf.all.rp_filter=2"
  - "net.ipv4.tcp_syncookies=1"
  - "net.ipv4.tcp_window_scaling=1"
nics_list:
  - nic: br-normal
    # type: bridge, interface
    type: bridge
  - nic: enp8s0f0
    type: interface
  - nic: enp8s0f1
    type: interface
  - nic: enp8s0f2
    type: interface
  - nic: enp8s0f3
    type: interface